# Workflow run on commits to release or main branches

name: Reusable Release Branch Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow when called by another workflow specific to a repository
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Validates schema of manifest.json
  schema_validation:
    # needs: security
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Skip CI')"
    steps:
      - uses: actions/checkout@v4
      - name: Validating schema of manifest.json
        shell: bash
        env:
          NPMRC_TOKEN: ${{ secrets.NPMRC_TOKEN }}
          ARGO_NPMRC_TOKEN: ${{ secrets.ARGO_NPMRC_TOKEN }}
          TEST_VALUE: ${{ secrets.TEST_VALUE }}
        run: |
          wget https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/node_setup.sh
          chmod +x node_setup.sh
          sh ./node_setup.sh
          wget https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/manifest-schema.json
          chmod +x manifest-schema.json
          wget https://raw.githubusercontent.com/Itential-Pre-Builts/common-utils/main/scripts/manifestTester.js
          chmod +x manifestTester.js
          node manifestTester.js manifest.json manifest-schema.json
