# Workflow run on commits to release or main branches

name: Reusable Release Branch Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow when called by another workflow specific to a repository
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Validates schema of manifest.json
  schema_validation:
    # needs: security
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Skip CI')"
    steps:
      - uses: actions/checkout@v4
      - name: Validating schema of manifest.json
        run: |
          ls -al